blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/woody-design/sonata/discussions/new?category=ideas
    about: Suggest a feature or improvement. Other users can upvote your idea.
  - name: Question
    url: https://github.com/woody-design/sonata/discussions/new?category=q-a
    about: Ask a question about using Sonata.
